version: '3'
services:

  dora-backend:
    image: dora-backend
    expose:
      - "5000"
    environment:
      - FLASK_PORT=5000

  dora-streamlit:
    image: dora-streamlit
    ports:
      - "8501:8501"
    environment:
      - FLASK_URL=http://flask:${FLASK_PORT}
    depends_on:
      - dora-backend

 
