version: '3'
services:
  dora-backend:
    image: dora-backend
    expose:
      - "5000"
    environment:
      - FLASK_PORT=5000
      - TOP_K_DOCUMENTS=10
      - MINIMUM_ACCURACY=0.50
      - FETCH_K_DOCUMENTS=100
      - ENV LAMBDA_MULT=0.2
      - ENV STRATEGY=similarity_score_threshold

  dora-streamlit:
    image: dora-streamlit
    ports:
      - "8501:8501"
    environment:
      - FLASK_URL=http://dora-backend:${FLASK_PORT}
    depends_on:
      - dora-backend

 
